### ISSUE TITLE
 Add "go get github.com/urfave/cli" in build section of readme

### ISSUE THREAD

**Issue by yhilem** [imesh/wso2-apim-cli#3]
Hi Imesh,

Can you plese modify the readme to add "go get github.com/urfave/cli" in build section :

git clone https://github.com/imesh/wso2-apim-cli
cd wso2-apim-cli
go get github.com/urfave/cli
go build .

Thanks,
Youcef HILEM

**Comment by imesh** [comment]
Hi Youcef,

Thanks for pointing this out. I just updated the README.md file with the instructions provided! Again, appreciate taking time for reporting this! 

Thanks
Imesh
